sample-app/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    
    get "static_pages/home", to: "static_pages#home"
    get "static_pages/about", to: "static_pages#about"
    get "static_pages/help", to: "static_pages#help"
    get "static_pages/contact", to: "static_pages#contact"
    get "users/signup", to: "users#new"
    get "sessions/login", to: "sessions#new"
    post "sessions/login", to: "sessions#create"
    delete "sessions/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(destroy show index)
    resources :relationships, only: [:create, :destroy]
    resources :microposts, only: [:create, :destroy]
    resources :users do
      member do
        get "followers", to: "followers#index"
        get "following", to: "followings#index"
      end
    end
  end
end

sample-app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?

    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.by_created_at.page(params[:page]).per Settings.record_per_page
  end

  def help; end
  
  def about; end

  def contact; end 
end

sample-app/app/helpers/static_pages_helper.rb
class StaticPagesController < ApplicationController
    def home; end
    def help; end
    def about; end
    def contact; end
  end

sample-app/app/views/static_pages/about.html.erb
<%= provide :title, t(".title") %>
<h2><%= t ".title" %></h2>
<p>
  <%= link_to t("book.title"), Settings.book.link, target:"_blank" %>
  <%= link_to t("static_pages.about.screen"), Settings.about.screen %>
  <%= link_to t("static_pages.about.ruby_on_rails"), Settings.about.rubyonrails %>
</p>

sample-app/app/views/static_pages/contact.html.erb
<%= provide :title, t(".title") %>

sample-app/app/views/static_pages/help.html.erb
<%= provide :title, t(".title") %>
<h2><%= t ".title" %></h2>
<p>
  <%= link_to t("static_pages.help.help_page"), Settings.help.url %>
  <%= link_to t("book.title"), Settings.help.book %>
</p>

sample-app/app/views/static_pages/home.html.erb
<%= provide :title, t("static_pages.home.title") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t "microposts.micropost_feed" %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t "static_pages.home.greeting" %></h1>
    <h2>
      <%= t "static_pages.home.home_page" %>
      <%= link_to t("book.title"), Settings.book.link %>
      <%= t "static_pages.home.application" %>
    </h2>
    <%= link_to t(".signup"), users_signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <%= link_to image_tag("rails.png", class: "logo", alt: "Rails logo"), Settings.book.link %>
<% end %>