sample-app/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    
    get "static_pages/home", to: "static_pages#home"
    get "static_pages/about", to: "static_pages#about"
    get "static_pages/help", to: "static_pages#help"
    get "static_pages/contact", to: "static_pages#contact"
    get "users/signup", to: "users#new"
    get "sessions/login", to: "sessions#new"
    post "sessions/login", to: "sessions#create"
    delete "sessions/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(destroy show index)
    resources :relationships, only: [:create, :destroy]
    resources :microposts, only: [:create, :destroy]
    resources :users do
      member do
        get "followers", to: "followers#index"
        get "following", to: "followings#index"
      end
    end
  end
end

sample-app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "layout.footer.the" %>
    <%= link_to t("book.title"), Settings.book.link %>
    <%= t "layout.footer.by" %>
    <%= link_to t("book.author"), Settings.book.link_author %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"), static_pages_about_path %></li>
      <li><%= link_to t("static_pages.contact.title"), static_pages_contact_path %></li>
      <li><%= link_to t("book.news"), Settings.book.news %>
    </ul>
  </nav>
</footer>

sample-app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".sample_app"), static_pages_home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.title"), static_pages_home_path %></li>
        <li><%= link_to t("static_pages.about.title"), static_pages_about_path %></li>
        <li><%= link_to t("static_pages.help.title"), static_pages_help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users.title"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t "users.acount.title" %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to t("settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t("logout"), sessions_logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("sessions.new.title"), sessions_login_path %></li>
        <% end %>
        <li class="lang">
          <%= t "lang" %>
          <ul>
            <li><%= link_to t("vietnam"), locale: "vi" %></li>
            <li><%= link_to t("english"), locale: "en" %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

sample-app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

sample-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> 
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>